name: Maven Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the release (e.g. 1.0.0)'
        required: true
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

run-name: Create release v${{ inputs.version }}

permissions:
  contents: write

jobs:
  release:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - uses: s4u/maven-settings-action@v3.0.0
        with:
          servers: |
            [{
              "id": "rettichlp",
              "username": "${{ secrets.MAVEN_NAME }}",
              "password": "${{ secrets.MAVEN_SECRET }}"
            }]

      - name: Deploy with Maven
        run: mvn deploy -Dmaven.test.skip

      - name: Create release notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          tag: v${{ inputs.version }}
        run: |
          gh release create "$tag" \
              --target main \
              --repo="$GITHUB_REPOSITORY" \
              --title="Release v$tag" \
              --generate-notes
